stages:
  - test

default:
  interruptible: true

.hello_ATS:
  stage: test
  script:
    - python2 -m virtualenv --python=python2.7 TEST_VENV
    - source TEST_VENV/bin/activate
    - pip install .
    - cd test/HelloATS
    - mpicc hello_ats.c
    - atslite1
    - cd $OLDPWD
    - >
      .gitlab/assert_ats_results.awk -v PASSED=22 FAILED=12 SKIPPED=10
      test/HelloATS/$SYS_TYPE*.logs/ats.log
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

hello_ATS_TOSS:
  extends: .hello_ATS
  tags:
    - shell
    - quartz

hello_ATS_BLUEOS:
  extends: .hello_ATS
  tags:
    - shell
    - lassen
