include:
  - local: .gitlab/kripke.yml
  - local: .gitlab/runners.yml

stages:
  - test

default:
  interruptible: true

.install_ATS:
  before_script:
    - ml python/3.8
    - python3 -m virtualenv --python=python3.8 TEST_VENV
    - source TEST_VENV/bin/activate
    - pip install .
    - pip install pyyaml
    - pip install cffi

.hello_ATS:
  extends: .install_ATS
  stage: test
  script:
    - cd test/HelloATS
    - mpicc hello_ats.c
    - atslite1
    - cd $OLDPWD
    - >
      .gitlab/assert_ats_results.awk -v PASSED=22 FAILED=12 SKIPPED=10
      test/HelloATS/$SYS_TYPE*.logs/ats.log

.hello_Flux:
  extends: .install_ATS
  stage: test
  variables:
    BANK: cbronze
  script:
    - cd test/HelloATS
    - mpicc hello_ats.c
    - python3 create_test_ats.py
    - atsflux --account=${BANK} test.ats
    - cd $OLDPWD
    - >
      .gitlab/assert_ats_results.awk -v PASSED=22 FAILED=12 SKIPPED=10
      test/HelloATS/flux00*.logs/ats.log
    - rm -rf *.logs

hello_ATS_TOSS:
  extends: [.hello_ATS, .run_quartz_shell]

hello_flux_TOSS:
  extends: [.hello_Flux, .run_quartz_shell]

#hello_ATS_BLUEOS:
#  extends: [.hello_ATS, .run_lassen_shell]

test-kripke:
  stage: test
  extends: .run_quartz_shell
  before_script:
    - !reference [.install_ATS, before_script]
    - !reference [.kripke_setup, before_script]
  script:
    - !reference [.kripke_test, script]
