include:
  - local: .gitlab/kripke.yml
  - local: .gitlab/runners.yml

stages:
  - test

default:
  interruptible: true

.install_ATS:
  before_script:
    - ml python/3.8
    - python3 -m virtualenv --python=python3.8 TEST_VENV
    - source TEST_VENV/bin/activate
    - pip install .

.hello_ATS:
  extends: .install_ATS
  stage: test
  script:
    - cd test/HelloATS
    - mpicc hello_ats.c
    - atslite1
    - cd $OLDPWD
    - >
      .gitlab/assert_ats_results.awk -v PASSED=22 FAILED=12 SKIPPED=10
      test/HelloATS/$SYS_TYPE*.logs/ats.log

hello_ATS_TOSS:
  extends: [.hello_ATS, .run_borax_shell]

#hello_ATS_BLUEOS:
#  extends: [.hello_ATS, .run_lassen_shell]

test-kripke:
  extends: .run_quartz_shell
  before_script:
    - !reference [.install_ATS, before_script]
    - !reference [.kripke_setup, before_script]
  script:
    - !reference [.kripke_test, script]
