name: Test ATS

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install_ats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ats-tool: [ats, ats3, atsflux, atsformat, atslite1, atslite3]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ATS
        run: python -m pip install .
      - name: which ATS tools
        run: which ${{ matrix.ats-tool }}
